### ISSUE TITLE
phylogenetic: Stochastic augur refine error with negative clock rate

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/dengue#82]
Noting the stochastic error in the `all` serotype build that I've seen in the automated runs:
- [2024-07-11](https://github.com/nextstrain/dengue/actions/runs/9895583176/job/27336481156#step:13:3319)
- [2024-07-24](https://github.com/nextstrain/dengue/actions/runs/10080925615/job/27872565326#step:13:2180)
- [2024-11-25](https://github.com/nextstrain/dengue/actions/runs/12015043740/job/33493289517#step:13:3213)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/treetime/treetime.py", line 57, in run
    return self._run(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/treetime/treetime.py", line 333, in _run
    self.calc_rate_susceptibility(params=tt_kwargs)
  File "/usr/local/lib/python3.10/site-packages/treetime/clock_tree.py", line 866, in calc_rate_susceptibility
    raise ValueError("ClockTree.calc_rate_susceptibility: rate estimate is negative. In this case the heuristic treetime uses to account for uncertainty in the rate estimate does not work. Please specify the clock-rate and its standard deviation explicitly via CLI parameters or arguments.")
ValueError: ClockTree.calc_rate_susceptibility: rate estimate is negative. In this case the heuristic treetime uses to account for uncertainty in the rate estimate does not work. Please specify the clock-rate and its standard deviation explicitly via CLI parameters or arguments.

ERROR: ClockTree.calc_rate_susceptibility: rate estimate is negative. In this case the heuristic treetime uses to account for uncertainty in the rate estimate does not work. Please specify the clock-rate and its standard deviation explicitly via CLI parameters or arguments. 
 
ERROR in TreeTime.run: An error occurred which was not properly handled in TreeTime. If this error persists, please let us know by filing a new issue including the original command and the error above at: https://github.com/neherlab/treetime/issues 

ERROR from TreeTime: An error occurred in TreeTime (see above). This may be due to an issue with TreeTime or Augur.
Please report you are calling TreeTime via Augur.
```

**Comment by ammaraziz** [comment]
@joverlee521 what causes this error? I have seen it before in my other builds but never tracked it down.

**Comment by joverlee521** [comment]
@ammaraziz I have not dug into the error so I'm not entirely sure. My guess is the stochastic error is caused by the random subsampling, but I also have not seen this error in a while.
